add copyright

diff --git a/pxe/bin/bootandrun b/pxe/bin/bootandrun
--- a/pxe/bin/bootandrun
+++ b/pxe/bin/bootandrun
@@ -1,6 +1,22 @@
 #!/bin/sh
 #
 #exec tclsh "$0" "$@"
+
+# backuPXE - Copyright (C) 2006-2019 Luc Deschenaux
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU Affero General Public License as
+# published by the Free Software Foundation, either version 3 of the
+# License, or (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU Affero General Public License for more details.
+
+# You should have received a copy of the GNU Affero General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
 . /pxe/etc/config
 
 PXEUSER=Administrateur
@@ -22,15 +38,15 @@ restartmachine () {
      ping $ip -W 2 -c 1 > /dev/null 2>&1 || return 0
 
      ssh -o strictHostKeyChecking=no -o PasswordAuthentication=no root@$ip /sbin/reboot > /dev/null 2>&1 && return $?
-     ssh -o strictHostKeyChecking=no -o PasswordAuthentication=no $PXEUSER@$ip shutdown -r -c Sorry -t 3 -f > /dev/null 2>&1 
+     ssh -o strictHostKeyChecking=no -o PasswordAuthentication=no $PXEUSER@$ip shutdown -r -c Sorry -t 3 -f > /dev/null 2>&1
      return $?
 
 }
 
 wakeupmachine () {
-  
+
   timer=90
-  
+
   rm $LOGDIR/problem 2> /dev/null || true
   rm $LOGDIR/done 2> /dev/null || true
   rm $LOGDIR/busy 2> /dev/null || true
@@ -41,7 +57,7 @@ wakeupmachine () {
   chmod a+rw $LOGDIR -R
 
   while [ $timer -gt 0 ] ; do
-    
+
     if [ -n "$ip" ] ; then
       bcast=`echo $ip | sed -r -n -e 's/^([0-9]+\.[0-9]+\.[0-9]+\.).*/\1/p'`255
       wakeonlan -p 9 -i $bcast $macaddr > /dev/null 2>&1
@@ -51,13 +67,13 @@ wakeupmachine () {
         wakeonlan -p 9 -i $destip $macaddr > /dev/null 2>&1
       done
     fi
-    
+
     [ ! -f $LOGDIR/ready ] && break
-    sleep 5 
+    sleep 5
     timer=`expr $timer - 10`
 
   done
- 
+
    restorepxebootfile
 
    if  [ $timer -eq 0 ] ; then
@@ -70,7 +86,7 @@ wakeupmachine () {
 usage='usage: bootandrun <mac_address|netbios_name|number> <pxe_config> [ <name>=<value> ... ] [ <command> [<args>] ]'
 if echo $1 | egrep -q '^[0-9]+$' ; then
    macaddr=`getrec /pxe/etc/machines $1`
-else 
+else
   while true; do
     netbiosname=`echo $1 | tr a-z A-Z`
     macaddr=`egrep -i " $netbiosname\$" /pxe/etc/hosts.mac | cut -f 1 -d ' '`
@@ -91,7 +107,7 @@ else
 fi
 
 if [ -z "$macaddr" ] ; then
-  echo "error: cant guess mac address" 
+  echo "error: cant guess mac address"
   exit 1
 fi
 
@@ -121,7 +137,7 @@ if [ -f $PXEBOOTFILE ] ; then
         echo `logprefix` error: `ls -l $PXEBOOTFILE | sed -r -n -e 's/[^\/]+//p'` is active$BR
         exit 1
    fi
-   if ! mv $PXEBOOTFILE $PXEBOOTFILE.tmp 2> /dev/null ; then 
+   if ! mv $PXEBOOTFILE $PXEBOOTFILE.tmp 2> /dev/null ; then
      echo `logprefix` error: cannot create $PXEBOOTFILE.tmp$BR
      exit 1
    fi
@@ -196,7 +212,7 @@ if [ -n "$ip" ] ; then
       while ping -W 2 -c 1 $ip > /dev/null 2>&1 ; do
         sleep 1
       done
-    fi 
+    fi
 fi
 
 echo `logprefix` notice: waiting for $macaddr to wake up$BR
